export enum ECrateContractMessageType {
  ContractCreated = "ContractCreated",
  SupplyUpdate = "SupplyUpdate",
  PriceUpdate = "PriceUpdate",
  RoyaltiesUpdate = "RoyaltiesUpdate",
  OwnershipTransferred = "OwnershipTransferred",
  // Transfer = "Transfer",
  Paused = "Paused",
  Unpaused = "Unpaused",
  ListMinted = "ListMinted",
  MintListUpdate = "MintListUpdate",
  MintListDeleted = "MintListDeleted",
  TreasuryUpdate = "TreasuryUpdate",
  FeeUpdate = "FeeUpdate",
  ReferralFeeUpdate = "ReferralFeeUpdate",
  Referral = "Referral",
}
