export const LICENSE_BLOCK = `# SPDX-License-Identifier: LicenseRef-AllRightsReserved
#
# License-Url: https://github.com/beramarket/torchbearer/LICENSES/LicenseRef-AllRightsReserved.txt
#
# SPDX-FileType: SOURCE
#
# SPDX-FileCopyrightText: 2024 Johannes Krauser III <detroitmetalcrypto@gmail.com>
#
# SPDX-FileContributor: Johannes Krauser III <detroitmetalcrypto@gmail.com>

# This file is generated by generateSchema.ts. Do not modify it manually.
# import { Decimal } from 'decimal.js';
\n
`

export const JAVASCRIPT_LICENSE_BLOCK = `/* 
* SPDX-License-Identifier: LicenseRef-AllRightsReserved
*
* License-Url: https://github.com/beramarket/torchbearer/LICENSES/LicenseRef-AllRightsReserved.txt
*
* SPDX-FileType: SOURCE
*
* SPDX-FileCopyrightText: 2024 Johannes Krauser III <detroitmetalcrypto@gmail.com>
*
* SPDX-FileContributor: Johannes Krauser III <detroitmetalcrypto@gmail.com>

* This file is generated by generateSchemaTypes.ts. Do not modify it manually.
*/
import { Decimal } from 'decimal.js';\n
`
